name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Use Node.js
      uses: actions/setup-node@v2
    - name: vuepress
      runs: |
        npm install 
        npm run vuepress:build

    - name: Deploy
      # 将构建产物 commit 到一个分支上，用于发布静态站点资源
      # https://github.com/peaceiris/actions-gh-pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        # Github 会在 workflow 中自动生成 GIHUBT_TOKEN，用于认证 workflow 的运行
        github_token: ${{ secrets.ACCESS_TOKEN }}
        # 静态资源目录设置
        publish_dir: .vuepress/dist/
        # 默认发布到 gh-pages 分支上，可以指定特定的发布分支（不能选拉取代码的分支）
        publish_branch: gh-pages
        full_commit_message: ${{ github.event.head_commit.message }}