name: Build and Deploy
on: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          cache: 'yarn'
      - run: |
          yarn install


      # 查看 workflow 的文档来获取更多信息
      # - name: Deploy to GitHub Pages
      #   uses: crazy-max/ghaction-github-pages@v2
      #   # 环境变量
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     # 部署到 gh-pages 分支
      #     target_branch: gh-pages
      #     # 部署目录为 VuePress 的默认输出目录
      #     build_dir: docs


      - name: Force push to destination branch
        uses: ad-m/github-push-action@v0.5.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # this might change depending on whether you are publishing a site for a normal repo or a user/organization repo
          branch: gh-pages
          directory: docs/.vuepress

      # - name: Init new repo in dist folder and commit generated files
      #   run: |
      #     cd docs/.vuepress/dist
      #     git init
      #     git add -A
      #     git config --local user.email "1084662708@qq.com"
      #     git config --local user.name "sword4869"
      #     git commit -m 'deploy'



# jobs:
#   build-and-deploy:
#     runs-on: ubuntu-22.04
#     steps:
    
#     - name: Checkout
#       uses: actions/checkout@v2

#     - name: vuepress-deploy
#       uses: jenkey2011/vuepress-deploy@master
#       env:
#         ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
#         TARGET_BRANCH: gh-pages
#         BUILD_SCRIPT: yarn install && yarn vuepress:build
#         BUILD_DIR: docs/.vuepress/dist/
    
# -----------------------------想不通为什么下面的失败了, /node_modules/mini-css-extract-plugin/dist/loader.js----------------------------------------
# - name: Setup Node.js
#   uses: actions/setup-node@v1
#   with:
#     node-version: 16

# - name: vuepress build
#   run: |
#     yarn install
#     yarn vuepress:build

# - name: gitpush
#   # 将构建产物 commit 到一个分支上，用于发布静态站点资源
#   # https://github.com/peaceiris/actions-gh-pages
#   uses: peaceiris/actions-gh-pages@v3
#   with:
#     # Github 会在 workflow 中自动生成 GIHUBT_TOKEN，用于认证 workflow 的运行
#     github_token: ${{ secrets.ACCESS_TOKEN }}
#     # 静态资源目录设置
#     publish_dir: docs/.vuepress/dist/
#     # 默认发布到 gh-pages 分支上，可以指定特定的发布分支（不能选拉取代码的分支）
#     publish_branch: gh-pages
#     full_commit_message: ${{ github.event.head_commit.message }}